### ISSUE TITLE
ath10k testen 17.01 vs. master

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#291]
Mein MAC1200R läuft prima mit dem LEDE master, aber nicht mit lede-17.02 wegen ath10k Fehlern - das betrifft auch die Archer C7 von Rene und eventuell mehr Hardware. Mal testen woran das liegt und wenn möglich fixen.

**Comment by kaese77** [comment]
Ich bin Die wieder da. Können wir uns mal anschauen.
VG, René
-------- Ursprüngliche Nachricht --------Von: Martin Tippmann <notifications@github.com> Datum: 28.07.17  16:06  (GMT+01:00) An: weimarnetz/weimarnetz <weimarnetz@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [weimarnetz/weimarnetz] ath10k testen 17.01 vs. master (#291) 
Mein MAC1200R läuft prima mit dem LEDE master, aber nicht mit lede-17.02 wegen ath10k Fehlern - das betrifft auch die Archer C7 von Rene und eventuell mehr Hardware. Mal testen woran das liegt und wenn möglich fixen.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/weimarnetz/weimarnetz","title":"weimarnetz/weimarnetz","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/weimarnetz/weimarnetz"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"ath10k testen 17.01 vs. master (#291)"}],"action":{"name":"View Issue","url":"https://github.com/weimarnetz/weimarnetz/issues/291"}}}

**Comment by mtippmann** [comment]
ath10k-ct patch wiederbeleben.

**Comment by mtippmann** [comment]
läuft auch ohne kmod-ath10-ct stabil, brauchen nur den ap-ibss patch und ath10k-ct firmware für ibss... läuft jetzt auch stabil auf archer 60v2
